### ISSUE TITLE
Examples and documentation

### ISSUE THREAD

**Issue by franzgranlund** [mobius-software-ltd/corsac-diameter#93]
Hi! 

I [read that you guys are developing](https://github.com/RestComm/jdiameter/pull/170#issuecomment-1918943146) a new diameter stack and not working on jdiameter anymore. 

Is this already ready for production? Can I find some examples or documentation somewhere, like, implementing a basic Rf server or similar?

Thanks!

**Comment by yulianoifa-mobius** [comment]
Hi
Yes , its ready for production. We have commercial version with clustering and other commercial features available.
As for documentation we are working on it.
You can follow it here: 
https://www.mobius-software.com/documentation/Mobius+Diameter
